//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace iOrder.Infrastructure.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class DocBoxLine : BaseEntity
    {
        public long OID { get; set; }
        public Nullable<int> CID { get; set; }
        public long BoxID { get; set; }
        public long DocID { get; set; }
        public bool IsRemoved { get; set; }
        public int Ordinal { get; set; }
        public Nullable<System.DateTime> RemoveDate { get; set; }
        public byte[] TST { get; set; }
    }
}
