//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace iOrder.Infrastructure.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Filial : BaseEntity
    {
        public Filial()
        {
            this.IconIndex = -1;
        }
    
        public long OID { get; set; }
        public Nullable<int> CID { get; set; }
        public Nullable<long> AddressID { get; set; }
        public string Comments { get; set; }
        public Nullable<System.DateTime> DelDate { get; set; }
        public string Email { get; set; }
        public string ExtraCode { get; set; }
        public string Fax { get; set; }
        public string FullName { get; set; }
        public string FullTextSearch { get; set; }
        public System.Guid GUID { get; set; }
        public int IconIndex { get; set; }
        public string InnerCode { get; set; }
        public bool IsDeleted { get; set; }
        public Nullable<long> ManagerID { get; set; }
        public string Name { get; set; }
        public Nullable<long> OwnerID { get; set; }
        public string PaperRegistrationCode { get; set; }
        public Nullable<long> ParentID { get; set; }
        public string Phone { get; set; }
        public Nullable<long> SID { get; set; }
        public byte[] TST { get; set; }
    }
}
