//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace iOrder.Infrastructure.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class TaxType : BaseEntity
    {
        public long OID { get; set; }
        public Nullable<int> CID { get; set; }
        public string FullName { get; set; }
        public System.Guid GUID { get; set; }
        public string Name { get; set; }
        public byte[] TST { get; set; }
        public string Value { get; set; }
    }
}
