// <auto-generated />
// This file was generated by a T4 template.
// Don't change it directly as your change would get overwritten.  Instead, make changes
// to the .tt file (i.e. the T4 template) and save it to regenerate this file.

// Make sure the compiler doesn't complain about missing Xml comments and CLS compliance
#pragma warning disable 1591, 3008, 3009
#region T4MVC

using System;
using System.Diagnostics;
using System.CodeDom.Compiler;
using System.Collections.Generic;
using System.Linq;
using System.Runtime.CompilerServices;
using System.Threading.Tasks;
using System.Web;
using System.Web.Hosting;
using System.Web.Mvc;
using System.Web.Mvc.Ajax;
using System.Web.Mvc.Html;
using System.Web.Routing;
using T4MVC;
namespace iOrder.Controllers
{
    public partial class AccountController
    {
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected AccountController(Dummy d) { }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected RedirectToRouteResult RedirectToAction(ActionResult result)
        {
            var callInfo = result.GetT4MVCResult();
            return RedirectToRoute(callInfo.RouteValueDictionary);
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected RedirectToRouteResult RedirectToAction(Task<ActionResult> taskResult)
        {
            return RedirectToAction(taskResult.Result);
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected RedirectToRouteResult RedirectToActionPermanent(ActionResult result)
        {
            var callInfo = result.GetT4MVCResult();
            return RedirectToRoutePermanent(callInfo.RouteValueDictionary);
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected RedirectToRouteResult RedirectToActionPermanent(Task<ActionResult> taskResult)
        {
            return RedirectToActionPermanent(taskResult.Result);
        }


        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public AccountController Actions { get { return MVC.Account; } }
        [GeneratedCode("T4MVC", "2.0")]
        public readonly string Area = "";
        [GeneratedCode("T4MVC", "2.0")]
        public readonly string Name = "Account";
        [GeneratedCode("T4MVC", "2.0")]
        public const string NameConst = "Account";

        static readonly ActionNamesClass s_actions = new ActionNamesClass();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionNamesClass ActionNames { get { return s_actions; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionNamesClass
        {
            public readonly string Login = "Login";
            public readonly string Logout = "Logout";
            public readonly string Register = "Register";
            public readonly string AddNewUser = "AddNewUser";
            public readonly string ChangePassword = "ChangePassword";
            public readonly string RestorePassword = "RestorePassword";
            public readonly string ConfirmPassword = "ConfirmPassword";
            public readonly string ShowRestorePasswordResult = "ShowRestorePasswordResult";
            public readonly string TopMenuLinks = "TopMenuLinks";
            public readonly string LeftMenuLinks = "LeftMenuLinks";
            public readonly string UserProfile = "UserProfile";
            public readonly string CodaUserProfileInfo = "CodaUserProfileInfo";
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionNameConstants
        {
            public const string Login = "Login";
            public const string Logout = "Logout";
            public const string Register = "Register";
            public const string AddNewUser = "AddNewUser";
            public const string ChangePassword = "ChangePassword";
            public const string RestorePassword = "RestorePassword";
            public const string ConfirmPassword = "ConfirmPassword";
            public const string ShowRestorePasswordResult = "ShowRestorePasswordResult";
            public const string TopMenuLinks = "TopMenuLinks";
            public const string LeftMenuLinks = "LeftMenuLinks";
            public const string UserProfile = "UserProfile";
            public const string CodaUserProfileInfo = "CodaUserProfileInfo";
        }


        static readonly ActionParamsClass_Login s_params_Login = new ActionParamsClass_Login();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_Login LoginParams { get { return s_params_Login; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_Login
        {
            public readonly string loginData = "loginData";
            public readonly string returnUrl = "returnUrl";
        }
        static readonly ActionParamsClass_Register s_params_Register = new ActionParamsClass_Register();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_Register RegisterParams { get { return s_params_Register; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_Register
        {
            public readonly string registerData = "registerData";
        }
        static readonly ActionParamsClass_AddNewUser s_params_AddNewUser = new ActionParamsClass_AddNewUser();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_AddNewUser AddNewUserParams { get { return s_params_AddNewUser; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_AddNewUser
        {
            public readonly string registerData = "registerData";
        }
        static readonly ActionParamsClass_ChangePassword s_params_ChangePassword = new ActionParamsClass_ChangePassword();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_ChangePassword ChangePasswordParams { get { return s_params_ChangePassword; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_ChangePassword
        {
            public readonly string chgPwdData = "chgPwdData";
        }
        static readonly ActionParamsClass_RestorePassword s_params_RestorePassword = new ActionParamsClass_RestorePassword();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_RestorePassword RestorePasswordParams { get { return s_params_RestorePassword; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_RestorePassword
        {
            public readonly string model = "model";
        }
        static readonly ActionParamsClass_ConfirmPassword s_params_ConfirmPassword = new ActionParamsClass_ConfirmPassword();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_ConfirmPassword ConfirmPasswordParams { get { return s_params_ConfirmPassword; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_ConfirmPassword
        {
            public readonly string model = "model";
        }
        static readonly ActionParamsClass_CodaUserProfileInfo s_params_CodaUserProfileInfo = new ActionParamsClass_CodaUserProfileInfo();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_CodaUserProfileInfo CodaUserProfileInfoParams { get { return s_params_CodaUserProfileInfo; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_CodaUserProfileInfo
        {
            public readonly string userProfile = "userProfile";
        }
        static readonly ViewsClass s_views = new ViewsClass();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ViewsClass Views { get { return s_views; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ViewsClass
        {
            static readonly _ViewNamesClass s_ViewNames = new _ViewNamesClass();
            public _ViewNamesClass ViewNames { get { return s_ViewNames; } }
            public class _ViewNamesClass
            {
                public readonly string AddNewUser = "AddNewUser";
                public readonly string ChangePassword = "ChangePassword";
                public readonly string ConfirmPassword = "ConfirmPassword";
                public readonly string DirShowError = "DirShowError";
                public readonly string LeftMenuLinks = "LeftMenuLinks";
                public readonly string Login = "Login";
                public readonly string Register = "Register";
                public readonly string RestorePassword = "RestorePassword";
                public readonly string ShowRestorePasswordResult = "ShowRestorePasswordResult";
                public readonly string TopMenuLinks = "TopMenuLinks";
                public readonly string UserProfile = "UserProfile";
            }
            public readonly string AddNewUser = "~/Views/Account/AddNewUser.cshtml";
            public readonly string ChangePassword = "~/Views/Account/ChangePassword.cshtml";
            public readonly string ConfirmPassword = "~/Views/Account/ConfirmPassword.cshtml";
            public readonly string DirShowError = "~/Views/Account/DirShowError.cshtml";
            public readonly string LeftMenuLinks = "~/Views/Account/LeftMenuLinks.cshtml";
            public readonly string Login = "~/Views/Account/Login.cshtml";
            public readonly string Register = "~/Views/Account/Register.cshtml";
            public readonly string RestorePassword = "~/Views/Account/RestorePassword.cshtml";
            public readonly string ShowRestorePasswordResult = "~/Views/Account/ShowRestorePasswordResult.cshtml";
            public readonly string TopMenuLinks = "~/Views/Account/TopMenuLinks.cshtml";
            public readonly string UserProfile = "~/Views/Account/UserProfile.cshtml";
        }
    }

    [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
    public partial class T4MVC_AccountController : iOrder.Controllers.AccountController
    {
        public T4MVC_AccountController() : base(Dummy.Instance) { }

        [NonAction]
        partial void LoginOverride(T4MVC_System_Web_Mvc_ActionResult callInfo);

        [NonAction]
        public override System.Web.Mvc.ActionResult Login()
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.Login);
            LoginOverride(callInfo);
            return callInfo;
        }

        [NonAction]
        partial void LoginOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, iOrder.Models.Login loginData, string returnUrl);

        [NonAction]
        public override System.Web.Mvc.ActionResult Login(iOrder.Models.Login loginData, string returnUrl)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.Login);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "loginData", loginData);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "returnUrl", returnUrl);
            LoginOverride(callInfo, loginData, returnUrl);
            return callInfo;
        }

        [NonAction]
        partial void LogoutOverride(T4MVC_System_Web_Mvc_ActionResult callInfo);

        [NonAction]
        public override System.Web.Mvc.ActionResult Logout()
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.Logout);
            LogoutOverride(callInfo);
            return callInfo;
        }

        [NonAction]
        partial void RegisterOverride(T4MVC_System_Web_Mvc_ActionResult callInfo);

        [NonAction]
        public override System.Web.Mvc.ActionResult Register()
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.Register);
            RegisterOverride(callInfo);
            return callInfo;
        }

        [NonAction]
        partial void RegisterOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, iOrder.Models.Register registerData);

        [NonAction]
        public override System.Web.Mvc.ActionResult Register(iOrder.Models.Register registerData)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.Register);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "registerData", registerData);
            RegisterOverride(callInfo, registerData);
            return callInfo;
        }

        [NonAction]
        partial void AddNewUserOverride(T4MVC_System_Web_Mvc_ActionResult callInfo);

        [NonAction]
        public override System.Web.Mvc.ActionResult AddNewUser()
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.AddNewUser);
            AddNewUserOverride(callInfo);
            return callInfo;
        }

        [NonAction]
        partial void AddNewUserOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, iOrder.Models.Register registerData);

        [NonAction]
        public override System.Web.Mvc.ActionResult AddNewUser(iOrder.Models.Register registerData)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.AddNewUser);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "registerData", registerData);
            AddNewUserOverride(callInfo, registerData);
            return callInfo;
        }

        [NonAction]
        partial void ChangePasswordOverride(T4MVC_System_Web_Mvc_ActionResult callInfo);

        [NonAction]
        public override System.Web.Mvc.ActionResult ChangePassword()
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.ChangePassword);
            ChangePasswordOverride(callInfo);
            return callInfo;
        }

        [NonAction]
        partial void ChangePasswordOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, iOrder.Models.ChangePassword chgPwdData);

        [NonAction]
        public override System.Web.Mvc.ActionResult ChangePassword(iOrder.Models.ChangePassword chgPwdData)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.ChangePassword);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "chgPwdData", chgPwdData);
            ChangePasswordOverride(callInfo, chgPwdData);
            return callInfo;
        }

        [NonAction]
        partial void RestorePasswordOverride(T4MVC_System_Web_Mvc_ActionResult callInfo);

        [NonAction]
        public override System.Web.Mvc.ActionResult RestorePassword()
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.RestorePassword);
            RestorePasswordOverride(callInfo);
            return callInfo;
        }

        [NonAction]
        partial void RestorePasswordOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, iOrder.Models.RestorePassword model);

        [NonAction]
        public override System.Web.Mvc.ActionResult RestorePassword(iOrder.Models.RestorePassword model)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.RestorePassword);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "model", model);
            RestorePasswordOverride(callInfo, model);
            return callInfo;
        }

        [NonAction]
        partial void ConfirmPasswordOverride(T4MVC_System_Web_Mvc_ActionResult callInfo);

        [NonAction]
        public override System.Web.Mvc.ActionResult ConfirmPassword()
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.ConfirmPassword);
            ConfirmPasswordOverride(callInfo);
            return callInfo;
        }

        [NonAction]
        partial void ConfirmPasswordOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, iOrder.Models.RestorePasswordParam model);

        [NonAction]
        public override System.Web.Mvc.ActionResult ConfirmPassword(iOrder.Models.RestorePasswordParam model)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.ConfirmPassword);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "model", model);
            ConfirmPasswordOverride(callInfo, model);
            return callInfo;
        }

        [NonAction]
        partial void ShowRestorePasswordResultOverride(T4MVC_System_Web_Mvc_ActionResult callInfo);

        [NonAction]
        public override System.Web.Mvc.ActionResult ShowRestorePasswordResult()
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.ShowRestorePasswordResult);
            ShowRestorePasswordResultOverride(callInfo);
            return callInfo;
        }

        [NonAction]
        partial void TopMenuLinksOverride(T4MVC_System_Web_Mvc_PartialViewResult callInfo);

        [NonAction]
        public override System.Web.Mvc.PartialViewResult TopMenuLinks()
        {
            var callInfo = new T4MVC_System_Web_Mvc_PartialViewResult(Area, Name, ActionNames.TopMenuLinks);
            TopMenuLinksOverride(callInfo);
            return callInfo;
        }

        [NonAction]
        partial void LeftMenuLinksOverride(T4MVC_System_Web_Mvc_PartialViewResult callInfo);

        [NonAction]
        public override System.Web.Mvc.PartialViewResult LeftMenuLinks()
        {
            var callInfo = new T4MVC_System_Web_Mvc_PartialViewResult(Area, Name, ActionNames.LeftMenuLinks);
            LeftMenuLinksOverride(callInfo);
            return callInfo;
        }

        [NonAction]
        partial void UserProfileOverride(T4MVC_System_Web_Mvc_ActionResult callInfo);

        [NonAction]
        public override System.Web.Mvc.ActionResult UserProfile()
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.UserProfile);
            UserProfileOverride(callInfo);
            return callInfo;
        }

        [NonAction]
        partial void CodaUserProfileInfoOverride(T4MVC_System_Web_Mvc_JsonResult callInfo);

        [NonAction]
        public override System.Web.Mvc.JsonResult CodaUserProfileInfo()
        {
            var callInfo = new T4MVC_System_Web_Mvc_JsonResult(Area, Name, ActionNames.CodaUserProfileInfo);
            CodaUserProfileInfoOverride(callInfo);
            return callInfo;
        }

        [NonAction]
        partial void CodaUserProfileInfoOverride(T4MVC_System_Web_Mvc_JsonResult callInfo, iOrder.Models.CodaUserProfile userProfile);

        [NonAction]
        public override System.Web.Mvc.JsonResult CodaUserProfileInfo(iOrder.Models.CodaUserProfile userProfile)
        {
            var callInfo = new T4MVC_System_Web_Mvc_JsonResult(Area, Name, ActionNames.CodaUserProfileInfo);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "userProfile", userProfile);
            CodaUserProfileInfoOverride(callInfo, userProfile);
            return callInfo;
        }

    }
}

#endregion T4MVC
#pragma warning restore 1591, 3008, 3009
