// <auto-generated />
// This file was generated by a T4 template.
// Don't change it directly as your change would get overwritten.  Instead, make changes
// to the .tt file (i.e. the T4 template) and save it to regenerate this file.

// Make sure the compiler doesn't complain about missing Xml comments and CLS compliance
#pragma warning disable 1591, 3008, 3009
#region T4MVC

using System;
using System.Diagnostics;
using System.CodeDom.Compiler;
using System.Collections.Generic;
using System.Linq;
using System.Runtime.CompilerServices;
using System.Threading.Tasks;
using System.Web;
using System.Web.Hosting;
using System.Web.Mvc;
using System.Web.Mvc.Ajax;
using System.Web.Mvc.Html;
using System.Web.Routing;
using T4MVC;
namespace iOrder.Controllers
{
    public partial class DocumentController
    {
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected DocumentController(Dummy d) { }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected RedirectToRouteResult RedirectToAction(ActionResult result)
        {
            var callInfo = result.GetT4MVCResult();
            return RedirectToRoute(callInfo.RouteValueDictionary);
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected RedirectToRouteResult RedirectToAction(Task<ActionResult> taskResult)
        {
            return RedirectToAction(taskResult.Result);
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected RedirectToRouteResult RedirectToActionPermanent(ActionResult result)
        {
            var callInfo = result.GetT4MVCResult();
            return RedirectToRoutePermanent(callInfo.RouteValueDictionary);
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected RedirectToRouteResult RedirectToActionPermanent(Task<ActionResult> taskResult)
        {
            return RedirectToActionPermanent(taskResult.Result);
        }

        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.JsonResult GetDocuments()
        {
            return new T4MVC_System_Web_Mvc_JsonResult(Area, Name, ActionNames.GetDocuments);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.JsonResult GetLines()
        {
            return new T4MVC_System_Web_Mvc_JsonResult(Area, Name, ActionNames.GetLines);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.JsonResult SaveLines()
        {
            return new T4MVC_System_Web_Mvc_JsonResult(Area, Name, ActionNames.SaveLines);
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public DocumentController Actions { get { return MVC.Document; } }
        [GeneratedCode("T4MVC", "2.0")]
        public readonly string Area = "";
        [GeneratedCode("T4MVC", "2.0")]
        public readonly string Name = "Document";
        [GeneratedCode("T4MVC", "2.0")]
        public const string NameConst = "Document";

        static readonly ActionNamesClass s_actions = new ActionNamesClass();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionNamesClass ActionNames { get { return s_actions; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionNamesClass
        {
            public readonly string Index = "Index";
            public readonly string Documents = "Documents";
            public readonly string Lines = "Lines";
            public readonly string GetDocuments = "GetDocuments";
            public readonly string GetLines = "GetLines";
            public readonly string SaveLines = "SaveLines";
            public readonly string NewOrder = "NewOrder";
            public readonly string OrdersDraft = "OrdersDraft";
            public readonly string OrdersHistory = "OrdersHistory";
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionNameConstants
        {
            public const string Index = "Index";
            public const string Documents = "Documents";
            public const string Lines = "Lines";
            public const string GetDocuments = "GetDocuments";
            public const string GetLines = "GetLines";
            public const string SaveLines = "SaveLines";
            public const string NewOrder = "NewOrder";
            public const string OrdersDraft = "OrdersDraft";
            public const string OrdersHistory = "OrdersHistory";
        }


        static readonly ActionParamsClass_GetDocuments s_params_GetDocuments = new ActionParamsClass_GetDocuments();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_GetDocuments GetDocumentsParams { get { return s_params_GetDocuments; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_GetDocuments
        {
            public readonly string model = "model";
        }
        static readonly ActionParamsClass_GetLines s_params_GetLines = new ActionParamsClass_GetLines();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_GetLines GetLinesParams { get { return s_params_GetLines; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_GetLines
        {
            public readonly string documentID = "documentID";
        }
        static readonly ActionParamsClass_SaveLines s_params_SaveLines = new ActionParamsClass_SaveLines();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_SaveLines SaveLinesParams { get { return s_params_SaveLines; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_SaveLines
        {
            public readonly string model = "model";
        }
        static readonly ViewsClass s_views = new ViewsClass();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ViewsClass Views { get { return s_views; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ViewsClass
        {
            static readonly _ViewNamesClass s_ViewNames = new _ViewNamesClass();
            public _ViewNamesClass ViewNames { get { return s_ViewNames; } }
            public class _ViewNamesClass
            {
                public readonly string Documents = "Documents";
                public readonly string Index = "Index";
                public readonly string Lines = "Lines";
                public readonly string NewOrder = "NewOrder";
                public readonly string OrdersDraft = "OrdersDraft";
                public readonly string OrdersHistory = "OrdersHistory";
            }
            public readonly string Documents = "~/Views/Document/Documents.cshtml";
            public readonly string Index = "~/Views/Document/Index.cshtml";
            public readonly string Lines = "~/Views/Document/Lines.cshtml";
            public readonly string NewOrder = "~/Views/Document/NewOrder.cshtml";
            public readonly string OrdersDraft = "~/Views/Document/OrdersDraft.cshtml";
            public readonly string OrdersHistory = "~/Views/Document/OrdersHistory.cshtml";
        }
    }

    [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
    public partial class T4MVC_DocumentController : iOrder.Controllers.DocumentController
    {
        public T4MVC_DocumentController() : base(Dummy.Instance) { }

        [NonAction]
        partial void IndexOverride(T4MVC_System_Web_Mvc_ActionResult callInfo);

        [NonAction]
        public override System.Web.Mvc.ActionResult Index()
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.Index);
            IndexOverride(callInfo);
            return callInfo;
        }

        [NonAction]
        partial void DocumentsOverride(T4MVC_System_Web_Mvc_PartialViewResult callInfo);

        [NonAction]
        public override System.Web.Mvc.PartialViewResult Documents()
        {
            var callInfo = new T4MVC_System_Web_Mvc_PartialViewResult(Area, Name, ActionNames.Documents);
            DocumentsOverride(callInfo);
            return callInfo;
        }

        [NonAction]
        partial void LinesOverride(T4MVC_System_Web_Mvc_PartialViewResult callInfo);

        [NonAction]
        public override System.Web.Mvc.PartialViewResult Lines()
        {
            var callInfo = new T4MVC_System_Web_Mvc_PartialViewResult(Area, Name, ActionNames.Lines);
            LinesOverride(callInfo);
            return callInfo;
        }

        [NonAction]
        partial void GetDocumentsOverride(T4MVC_System_Web_Mvc_JsonResult callInfo, iOrder.Models.DocumentsParamsViewModel model);

        [NonAction]
        public override System.Web.Mvc.JsonResult GetDocuments(iOrder.Models.DocumentsParamsViewModel model)
        {
            var callInfo = new T4MVC_System_Web_Mvc_JsonResult(Area, Name, ActionNames.GetDocuments);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "model", model);
            GetDocumentsOverride(callInfo, model);
            return callInfo;
        }

        [NonAction]
        partial void GetLinesOverride(T4MVC_System_Web_Mvc_JsonResult callInfo, string documentID);

        [NonAction]
        public override System.Web.Mvc.JsonResult GetLines(string documentID)
        {
            var callInfo = new T4MVC_System_Web_Mvc_JsonResult(Area, Name, ActionNames.GetLines);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "documentID", documentID);
            GetLinesOverride(callInfo, documentID);
            return callInfo;
        }

        [NonAction]
        partial void SaveLinesOverride(T4MVC_System_Web_Mvc_JsonResult callInfo, iOrder.Models.LinesViewModel model);

        [NonAction]
        public override System.Web.Mvc.JsonResult SaveLines(iOrder.Models.LinesViewModel model)
        {
            var callInfo = new T4MVC_System_Web_Mvc_JsonResult(Area, Name, ActionNames.SaveLines);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "model", model);
            SaveLinesOverride(callInfo, model);
            return callInfo;
        }

        [NonAction]
        partial void NewOrderOverride(T4MVC_System_Web_Mvc_PartialViewResult callInfo);

        [NonAction]
        public override System.Web.Mvc.PartialViewResult NewOrder()
        {
            var callInfo = new T4MVC_System_Web_Mvc_PartialViewResult(Area, Name, ActionNames.NewOrder);
            NewOrderOverride(callInfo);
            return callInfo;
        }

        [NonAction]
        partial void OrdersDraftOverride(T4MVC_System_Web_Mvc_PartialViewResult callInfo);

        [NonAction]
        public override System.Web.Mvc.PartialViewResult OrdersDraft()
        {
            var callInfo = new T4MVC_System_Web_Mvc_PartialViewResult(Area, Name, ActionNames.OrdersDraft);
            OrdersDraftOverride(callInfo);
            return callInfo;
        }

        [NonAction]
        partial void OrdersHistoryOverride(T4MVC_System_Web_Mvc_PartialViewResult callInfo);

        [NonAction]
        public override System.Web.Mvc.PartialViewResult OrdersHistory()
        {
            var callInfo = new T4MVC_System_Web_Mvc_PartialViewResult(Area, Name, ActionNames.OrdersHistory);
            OrdersHistoryOverride(callInfo);
            return callInfo;
        }

    }
}

#endregion T4MVC
#pragma warning restore 1591, 3008, 3009
