// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by coded UI test builder.
//      Version: 12.0.0.0
//
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------

namespace CodaOrderTest
{
    using System;
    using System.CodeDom.Compiler;
    using System.Collections.Generic;
    using System.Drawing;
    using System.Text.RegularExpressions;
    using System.Windows.Input;
    using Microsoft.VisualStudio.TestTools.UITest.Extension;
    using Microsoft.VisualStudio.TestTools.UITesting;
    using Microsoft.VisualStudio.TestTools.UITesting.WinControls;
    using Microsoft.VisualStudio.TestTools.UnitTesting;
    using Keyboard = Microsoft.VisualStudio.TestTools.UITesting.Keyboard;
    using Mouse = Microsoft.VisualStudio.TestTools.UITesting.Mouse;
    using MouseButtons = System.Windows.Forms.MouseButtons;
    
    
    [GeneratedCode("Coded UITest Builder", "12.0.31101.0")]
    public partial class UIMap
    {
        
        /// <summary>
        /// Test_UserProfile_Controls - Use 'Test_UserProfile_ControlsParams' to pass parameters into this method.
        /// </summary>
        public void Test_UserProfile_Controls()
        {
            #region Variable Declarations
            WinControl uIChromeLegacyWindowDocument = this.UILoginMyASPNETApplicaWindow.UIChromeLegacyWindowWindow.UIChromeLegacyWindowDocument;
            WinWindow uIDocumentsIndexMyASPNWindow = this.UILoginMyASPNETApplicaWindow.UIDocumentsIndexMyASPNWindow;
            #endregion

            // Click 'Chrome Legacy Window' document
            Mouse.Click(uIChromeLegacyWindowDocument, new Point(752, 127));

            // Click 'Chrome Legacy Window' document
            Mouse.Click(uIChromeLegacyWindowDocument, new Point(704, 123));

            // Type '{Back}coda admin' in 'Chrome Legacy Window' document
            Keyboard.SendKeys(uIChromeLegacyWindowDocument, this.Test_UserProfile_ControlsParams.UIChromeLegacyWindowDocumentSendKeys, ModifierKeys.None);

            // Click 'Chrome Legacy Window' document
            Mouse.Click(uIChromeLegacyWindowDocument, new Point(711, 191));

            // Type '2222' in 'Chrome Legacy Window' document
            Keyboard.SendKeys(uIChromeLegacyWindowDocument, this.Test_UserProfile_ControlsParams.UIChromeLegacyWindowDocumentSendKeys1, ModifierKeys.None);

            // Click 'Chrome Legacy Window' document
            Mouse.Click(uIChromeLegacyWindowDocument, new Point(682, 242));

            // Click 'Chrome Legacy Window' document
            Mouse.Click(uIChromeLegacyWindowDocument, new Point(1318, 572));

            // Type 'Control, Shift + i' in 'Chrome Legacy Window' document
            Keyboard.SendKeys(uIChromeLegacyWindowDocument, this.Test_UserProfile_ControlsParams.UIChromeLegacyWindowDocumentSendKeys2, (ModifierKeys.Control | ModifierKeys.Shift));

            // Click 'Documents Index - My ASP.NET Application - Google ...' window
            Mouse.Click(uIDocumentsIndexMyASPNWindow, new Point(1084, 92));
        }
        
        #region Properties
        public virtual Test_UserProfile_ControlsParams Test_UserProfile_ControlsParams
        {
            get
            {
                if ((this.mTest_UserProfile_ControlsParams == null))
                {
                    this.mTest_UserProfile_ControlsParams = new Test_UserProfile_ControlsParams();
                }
                return this.mTest_UserProfile_ControlsParams;
            }
        }
        
        public UILoginMyASPNETApplicaWindow UILoginMyASPNETApplicaWindow
        {
            get
            {
                if ((this.mUILoginMyASPNETApplicaWindow == null))
                {
                    this.mUILoginMyASPNETApplicaWindow = new UILoginMyASPNETApplicaWindow();
                }
                return this.mUILoginMyASPNETApplicaWindow;
            }
        }
        #endregion
        
        #region Fields
        private Test_UserProfile_ControlsParams mTest_UserProfile_ControlsParams;
        
        private UILoginMyASPNETApplicaWindow mUILoginMyASPNETApplicaWindow;
        #endregion
    }
    
    /// <summary>
    /// Parameters to be passed into 'Test_UserProfile_Controls'
    /// </summary>
    [GeneratedCode("Coded UITest Builder", "12.0.31101.0")]
    public class Test_UserProfile_ControlsParams
    {
        
        #region Fields
        /// <summary>
        /// Type '{Back}coda admin' in 'Chrome Legacy Window' document
        /// </summary>
        public string UIChromeLegacyWindowDocumentSendKeys = "{Back}coda admin";
        
        /// <summary>
        /// Type '2222' in 'Chrome Legacy Window' document
        /// </summary>
        public string UIChromeLegacyWindowDocumentSendKeys1 = "2222";
        
        /// <summary>
        /// Type 'Control, Shift + i' in 'Chrome Legacy Window' document
        /// </summary>
        public string UIChromeLegacyWindowDocumentSendKeys2 = "i";
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "12.0.31101.0")]
    public class UILoginMyASPNETApplicaWindow : WinWindow
    {
        
        public UILoginMyASPNETApplicaWindow()
        {
            #region Search Criteria
            this.SearchProperties[WinWindow.PropertyNames.Name] = "Login - My ASP.NET Application - Google Chrome";
            this.SearchProperties[WinWindow.PropertyNames.ClassName] = "Chrome_WidgetWin_1";
            this.WindowTitles.Add("Login - My ASP.NET Application - Google Chrome");
            this.WindowTitles.Add("Documents Index - My ASP.NET Application - Google Chrome");
            #endregion
        }
        
        #region Properties
        public UIChromeLegacyWindowWindow UIChromeLegacyWindowWindow
        {
            get
            {
                if ((this.mUIChromeLegacyWindowWindow == null))
                {
                    this.mUIChromeLegacyWindowWindow = new UIChromeLegacyWindowWindow(this);
                }
                return this.mUIChromeLegacyWindowWindow;
            }
        }
        
        public WinWindow UIDocumentsIndexMyASPNWindow
        {
            get
            {
                if ((this.mUIDocumentsIndexMyASPNWindow == null))
                {
                    this.mUIDocumentsIndexMyASPNWindow = new WinWindow(this);
                    #region Search Criteria
                    this.mUIDocumentsIndexMyASPNWindow.SearchProperties[WinWindow.PropertyNames.Name] = "Documents Index - My ASP.NET Application - Google Chrome";
                    this.mUIDocumentsIndexMyASPNWindow.SearchConfigurations.Add(SearchConfiguration.DisambiguateChild);
                    this.mUIDocumentsIndexMyASPNWindow.WindowTitles.Add("Documents Index - My ASP.NET Application - Google Chrome");
                    #endregion
                }
                return this.mUIDocumentsIndexMyASPNWindow;
            }
        }
        #endregion
        
        #region Fields
        private UIChromeLegacyWindowWindow mUIChromeLegacyWindowWindow;
        
        private WinWindow mUIDocumentsIndexMyASPNWindow;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "12.0.31101.0")]
    public class UIChromeLegacyWindowWindow : WinWindow
    {
        
        public UIChromeLegacyWindowWindow(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[WinWindow.PropertyNames.ControlId] = "305644672";
            this.WindowTitles.Add("Login - My ASP.NET Application - Google Chrome");
            this.WindowTitles.Add("Documents Index - My ASP.NET Application - Google Chrome");
            #endregion
        }
        
        #region Properties
        public WinControl UIChromeLegacyWindowDocument
        {
            get
            {
                if ((this.mUIChromeLegacyWindowDocument == null))
                {
                    this.mUIChromeLegacyWindowDocument = new WinControl(this);
                    #region Search Criteria
                    this.mUIChromeLegacyWindowDocument.SearchProperties[UITestControl.PropertyNames.ControlType] = "Document";
                    this.mUIChromeLegacyWindowDocument.WindowTitles.Add("Login - My ASP.NET Application - Google Chrome");
                    this.mUIChromeLegacyWindowDocument.WindowTitles.Add("Documents Index - My ASP.NET Application - Google Chrome");
                    #endregion
                }
                return this.mUIChromeLegacyWindowDocument;
            }
        }
        #endregion
        
        #region Fields
        private WinControl mUIChromeLegacyWindowDocument;
        #endregion
    }
}
