//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication3.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Box : BaseEntity
    {
        public long OID { get; set; }
        public Nullable<int> CID { get; set; }
        public string BoxCode { get; set; }
        public long BoxTypeID { get; set; }
        public Nullable<System.DateTime> CloseDate { get; set; }
        public bool IsClosed { get; set; }
        public Nullable<System.DateTime> OpenDate { get; set; }
        public long OwnerID { get; set; }
    }
}
