//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace iOrder.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class DocTradeLine : BaseEntity
    {
        public long OID { get; set; }
        public Nullable<int> CID { get; set; }
        public decimal Available { get; set; }
        public decimal BasePrice { get; set; }
        public Nullable<long> CasefillrateID { get; set; }
        public decimal CostSum { get; set; }
        public Nullable<decimal> CustomPrice { get; set; }
        public decimal Discount { get; set; }
        public long DocID { get; set; }
        public int IconIndex { get; set; }
        public long ItemID { get; set; }
        public decimal Ordered { get; set; }
        public decimal Price { get; set; }
        public decimal Quantity { get; set; }
        public string SortNO { get; set; }
        public decimal VatPercent { get; set; }
        public decimal VatSum { get; set; }
    }
}
