//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace iOrder.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class JournalSale_Documents : BaseEntity
    {
        public JournalSale_Documents()
        {
            this.IconIndex = -1;
        }
    
        public long OID { get; set; }
        public Nullable<int> CID { get; set; }
        public Nullable<decimal> Amount { get; set; }
        public Nullable<long> BranchID { get; set; }
        public System.DateTime ChangeDate { get; set; }
        public string Comments { get; set; }
        public System.DateTime CreateDate { get; set; }
        public Nullable<System.DateTime> DelDate { get; set; }
        public string DocCode { get; set; }
        public System.DateTime DocDate { get; set; }
        public Nullable<long> EmployeeID { get; set; }
        public Nullable<long> DeliverID { get; set; }
        public Nullable<long> ReceiverID { get; set; }
        public long FirmID { get; set; }
        public string FullName { get; set; }
        public System.Guid GUID { get; set; }
        public int IconIndex { get; set; }
        public bool IsDeleted { get; set; }
        public string Name { get; set; }
        public Nullable<long> NodeID { get; set; }
        public string RGB { get; set; }
        public Nullable<long> SourceDocID { get; set; }
        public Nullable<long> DocGroupID { get; set; }
        public Nullable<long> DocGroupPosition { get; set; }
        public byte[] TST { get; set; }
        public decimal PriceSum { get; set; }
        public decimal VatSum { get; set; }
        public Nullable<long> ContractID { get; set; }
        public long CustomerID { get; set; }
        public Nullable<long> DepartmentID { get; set; }
        public Nullable<long> CorrespondID { get; set; }
        public string TaxCode { get; set; }
        public Nullable<System.DateTime> TaxDate { get; set; }
        public Nullable<long> FilialID { get; set; }
        public string PrintComments { get; set; }
        public int IsForeign { get; set; }
        public Nullable<long> RevenueID { get; set; }
        public Nullable<long> DelayLimit { get; set; }
        public decimal VatPercent { get; set; }
        public string SourceDocCode { get; set; }
        public bool IsChangedAfterPrint { get; set; }
        public Nullable<long> CasefillrateID { get; set; }
        public Nullable<long> SectorID { get; set; }
        public string CreditComments { get; set; }
        public Nullable<decimal> VATNNSum { get; set; }
        public string TaxInvoiceType { get; set; }
        public int LineCount { get; set; }
        public string Coordinate { get; set; }
        public string BrandName { get; set; }
    }
}
